# Generated by Django 4.2.23 on 2025-08-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_tag_issue_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slack_thread_ts',
            field=models.CharField(blank=True, help_text='Slack thread timestamp for notifications', max_length=50, null=True),
        ),
    ]
