# Generated by Django 4.2.23 on 2025-08-22 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_slack_thread_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when issue was deleted (null = not deleted)', null=True),
        ),
        migrations.CreateModel(
            name='IssueEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field that was edited', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value of the field')),
                ('new_value', models.TextField(blank=True, help_text='New value of the field')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_edits', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='issues.issue')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
